### ISSUE TITLE
Calculation of MaxChargeCurrent and MaxDischargeCurrent for only one Multiplus II

### ISSUE THREAD

**Issue by kakariki1** [Dr-Gigavolt/dbus-aggregate-batteries#10]
The current driver only works for systems having more than one Multiplus II like yours (3 phase system).

My system is one Multiplus II connected to two parallel-connected batteries.
In this case the calculation for maximum charge/discharge currents and maybe other values is different.

MaxChargeCurrent and MaxDischargeCurrent should be the lowest of all values.

Adding this option would be great ...

**Comment by Dr-Gigavolt** [comment]
I don't understand. If you disable own charge/discharge parameters calculation you receive the parameters from your both instances of the battery driver. Each one should be configured for only one battery. Therefore sum of currents and minimum of voltages. Why should it be dependend on quantity of multis?

**Comment by kakariki1** [comment]
I'll try to explain using following example:

The system is charging and allmost full, but the state-of-charge is slightly different.
The maximum cell voltage of battery 1 is 3.38V -> this results in a maximum charge current of i.e. 50A
The maximum cell voltage of battery 2 is 3.43V -> this results in a maximum charge current of i.e. 10A

If using the sum of currents (i.e. 60A) battery 2 is charged with too much current.
In this case I would like to charge using 2x 10A

Does this make sense ?

**Comment by Dr-Gigavolt** [comment]
Thanks for the details, I understand now. I can change it in this way. This week I have no time for it, but I'll do my best.

**Comment by kakariki1** [comment]
Okay, thanks and no hurry ;-)

**Comment by kakariki1** [comment]
If you're interested I attached the changed files.
Changes are marked by "lakeroe", hardcoded and the files are renamed to .txt
It's not fully tested yet, but works so far ...

[aggregatebatteries.txt](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/files/10543761/aggregatebatteries.txt)
[dbusmon.txt](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/files/10543762/dbusmon.txt)
[settings.txt](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/files/10543760/settings.txt)

**Comment by maxicus** [comment]
@kakariki1 
In such a different battery packs, I'd expect that internal resistance growth of cell will cause that once charger push 60A, it won't split it 1:1. i.e.:
- battery1 in your case will take lets say 40A, and 
- battery 2 will take 20A (since it's nearly charged and it's resistance start to grow)
Did you check that ratio in that case for your setup?

If my expectations are true and difference is substantial, limiting total current to 20A will leave a lot of space for optimization.

Other than that I agree that using min current will cause safer calculations for a generic case.

**Comment by kakariki1** [comment]
Here is a screenshot showing the charge current dependent on maximum cell voltage:

![grafik](https://user-images.githubusercontent.com/119927001/216151008-7d5ffe9b-33f1-4d01-a285-9ce36ce4a0a8.png)

It's not clearly visible but (for example) if maximum cell voltage of battery 1 is 3.43V then charge current is 4,92A.
At the same time maximum cell voltage of battery 2 is 3.38V then charge current is 12,91A.
So I agree, charge current does not take 1:1 !

How would you calculate charge current ?

**Comment by Dr-Gigavolt** [comment]
I see no reason to adapt the charge current. Your cells are not balanced yet. When they will be ballanced, both batteries will be full at the same time. So taking the lower current or own charge parameters is safer.

**Comment by kakariki1** [comment]
I'm sorry but I have to disagree. All cells were balanced as good as I could. I connected them all in parallel and charged them to 3.60V since the charge current was 0. I then let them sit for another day without power supply ...
In my opinion there will always be some imbalance due to small capacity differences ...

**Comment by Dr-Gigavolt** [comment]
Ok, if ballanced, then everything is fine. It will work well with the lowest current x N. It will be enough to transport the last fraction of charge and the balancers will do their job.

**Comment by Dr-Gigavolt** [comment]
Hi Lakeroe,
thanks for your proposals. I added it into my code and going to test for couple of days. Except of searching for minima of AllowToCharge/Discharge in case of OWN_CHARGE_PARAMETERS == False I put an additional safety feature for the case of 'True' - AllowToCharge/Discharge will be set to zero if the standard mechanism fails and the Min/MaxCellVoltage continues to be exceeded.

**Comment by Dr-Gigavolt** [comment]
AllowToCharge/Discharge has no effect, is only shown in GUI. The max. charge current is very coarse, I had over 10A if limited to zero. Only max. charge voltage has an reasonable accuracy to avoid overcharging.
