### ISSUE TITLE
SoC calculation incorrect

### ISSUE THREAD

**Issue by Leupi123** [Dr-Gigavolt/dbus-aggregate-batteries#22]
It seems the SoC calculation is not correct.
I´m currently using 2 different sized batteries (280Ah and 600Ah), the resulting SoC is as shown below:

![image](https://user-images.githubusercontent.com/127965633/228627306-7e5f4b66-3637-41d6-813e-5c2f7cb3852a.png)

But i would expect a SoC of 57%.

**Comment by Dr-Gigavolt** [comment]
You are right, I didn't think about different batteries. It is easy to correct. But do you trust the SoC measurement of your BMS if they show 10% difference although connected parallel?

**Comment by Dr-Gigavolt** [comment]
I changed it to weighted average. Will be available at the next update.

**Comment by Leupi123** [comment]
Thanks, I already installed the latest version. Looks good now!
