### ISSUE TITLE
Relationship MPPT/SmartShunt

### ISSUE THREAD

**Issue by jdeus** [Dr-Gigavolt/dbus-aggregate-batteries#29]
Hello,

What exactly is the relationship between MPPTs and SmartShunts when calculating the current ? (https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/blob/main/aggregatebatteries.py#L451) i.e. why is the current from the MPPTs added on top ?

There's already a setting for the SmartShunt which tells the GX to use it for current measurement and SOC ("System setup" > "Battery monitor"). Isn't that enough ? Priority for current measurement should be given to DVCC, if available, in my opinion.

Edit: There really should be an option to use the SmartShunt to determine SOC instead of the hacky way of using a text file (/data/dbus-aggregate-batteries/charge). Documentation : https://github.com/victronenergy/dbus-systemcalc-py#select-battery-service

Best

**Comment by Dr-Gigavolt** [comment]
Hi, this option is for DC consumption measured by Smart shunt. You can disable it if your shunts have other purpose.
