### ISSUE TITLE
Deporting the max charge current in dbus-serialbattery

### ISSUE THREAD

**Issue by jdeus** [Dr-Gigavolt/dbus-aggregate-batteries#30]
Wouldn't the logic behind adapting the max charge current depending on the voltage of the cells be better placed in the [dbus-serialbattery](https://github.com/Louisvdw/dbus-serialbattery) project itself ? It seems to have nothing to do with aggregating batteries. 

Instead, each battery bank should expose this metric and [dbus-aggregate-batteries](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries) should simply honor the charging current based on the min(banks.max_acceptable_current)

This would also allow to set different voltages per cell per battery, which would allow for example mixing different chemistries or even the same chemistry but with a different count of cells per bank (with lower cell voltage), amounting to the overall same bank voltage.

**Comment by Dr-Gigavolt** [comment]
Please read readme.md and comments in settings.py. You can disable this function and take the values from dbus-serial-battery. I don't understand how it works in dbus-serial-battery (too complex) and feel safer to use my calculation which is much simpler. Mixing cells as you propose ... I would never do it.
