### ISSUE TITLE
SOC and Amps from Lynx Shunt

### ISSUE THREAD

**Issue by gnissahr** [Dr-Gigavolt/dbus-aggregate-batteries#38]
Would it be possible to read the SOC and Amps from a Lynx Shunt?
Currently it seems to reed the Amps from the multiplus and SOC calculation is own. But the SOC does not reset to 100%. 

![image](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/assets/65919827/c7391e8f-7b21-40c0-aa87-8b3196fc47e3)
![image](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/assets/65919827/0afbadc8-72af-42af-bb5a-7fb729565626)

**Comment by Dr-Gigavolt** [comment]
Hello, there is no reason to use additional hardware as battery monitor. Either the BMS current and SOC are good (not my case), or by setting OWN_SOC = True and CURRENT_FROM_VICTRON = True. The SOC in this case is reset to 100% if overall battery voltage or the first cell reach the allowed maximum. And is reset to 0 in case of reaching minimum. It works perfectly in my case. SmartShunt can be activated for measuring of DC consumption. I cannot consider all possible hardware combinations, this would make the maintenance very difficult and I would not be able to to it in my limited time. But feel free to reverse engineer the program and modify your copy to fit your requirements.
