### ISSUE TITLE
Same battery "/CustomName" causing trouble by reading single cell voltages

### ISSUE THREAD

**Issue by Marvo2011** [Dr-Gigavolt/dbus-aggregate-batteries#41]
Hello,

the same battery "/CustomName" causing trouble by reading single cell voltages. The driver reads only the cell voltages from the first pack and ignore all other. 

Example:
2x Batterys with /CustomName = "JBD"

First Pack = cellVoltages = JBD_Cell1 etc..
Second Pack overrides, because of same name = cellVoltages = JBD_Cell1 etc..

I will try to fix it with https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/pull/13

**Comment by Dr-Gigavolt** [comment]
I hope it works now with 3.0
