### ISSUE TITLE
Value Remaining Time

### ISSUE THREAD

**Issue by dersch81** [Dr-Gigavolt/dbus-aggregate-batteries#43]
Hi, since serial battery is getting a lot of new features we also have remaining time now. Would you please add this to aggregate batteries?

**Comment by Dr-Gigavolt** [comment]
Hello, all versions of Serial Battery since Bluetooth added are unstable in my sxstem, I don't understand why. I use an old one. Please write all new dbus paths you would like to aggregate, I can add them.

**Comment by Dr-Gigavolt** [comment]
I added to my code, after test it will be published with an update.
