### ISSUE TITLE
No Data from Aggregate Batteries 

### ISSUE THREAD

**Issue by peregrines2** [Dr-Gigavolt/dbus-aggregate-batteries#46]
Yesterday I installed my 4th battery bank (JK BMS EVE280 Serialbattery). I adapted the settings in settings.py accordingly. 
I get the following error :( 
Using Venus V3.10 in Rpi4 8GB.

<img width="908" alt="Bildschirmfoto 2023-07-29 um 07 06 55" src="https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/assets/9152610/335110b7-8e28-4187-8f8f-78e5fc1e013d">

<img width="1078" alt="Bildschirmfoto 2023-07-29 um 07 10 08" src="https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/assets/9152610/fe650cd5-cec2-4517-81ae-052a8eb0b014">

**Comment by Dr-Gigavolt** [comment]
Hello, the Venus 3.10 is beta. I use 3.00 and everything works. Please try 3.00 or the last release 3.01. The log says that some Dbus path is invalid. When I'll do the next update of my code I'll add an exact messaging which path fails. But have no time at the moment, I'm sorry.

**Comment by Dr-Gigavolt** [comment]
I improved logging, it will be available with soon available with the next update.
