### ISSUE TITLE
charge file in wrong directory

### ISSUE THREAD

**Issue by dakoal** [Dr-Gigavolt/dbus-aggregate-batteries#6]
the "charge" file from the repository is in the "service" subfolder.

I put it into the main directory, now it works.

**Comment by Dr-Gigavolt** [comment]
In my case it works from service directory. Only if I start it from the main directory by python3 aggregatebatteries.py (for debugging) I need to put it into the main directory. I can set absolute paths if it is important for you.

**Comment by dakoal** [comment]
It was only in my case. I have CerboGX with Venus OS 2.92. Maybe a fixed path is better, I don't know.

**Comment by Dr-Gigavolt** [comment]
Now the files _charge_ and _aggregatebatteries.log_ are referenced by absolute path _/data/dbus-aggregate-batteries/_
