### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by coca7** [Dr-Gigavolt/dbus-aggregate-batteries#64]
Hello,

I have had trouble installing bus-aggregate-batteries.  I think I am making an error.
I wasn't sure how to copy the files to /data/dbus-aggregate-batteries so I just did a wget together the files and then I untried and and renamed the directory and adjusted the settings.  However, it doesn't seem to be running.

My setup is 3 JBD Bms each with 4x 230ah cells
I have a smart shunt, but I have not yet moved it to the DC side of my setup.

**Comment by coca7** [comment]
Here is what I put in settings:

> Last login: Sat Apr  6 13:17:14 on ttys001
padre@MacBookPro ~ % ssh root@192.168.2.133
root@192.168.2.133's password: 
Last login: Sat Apr  6 18:19:44 2024 from 192.168.2.171
root@einstein:~# cd /
root@einstein:/# ls
Settings    dev         lost+found  proc        sys
bin         etc         media       run         tmp
boot        home        mnt         sbin        usr
data        lib         opt         service     var
root@einstein:/# cd data/
root@einstein:/data# cd dbus-aggregate-batteries/
root@einstein:/data/dbus-aggregate-batteries# ls
root@einstein:/data/dbus-aggregate-batteries# wget https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/archive/refs/tags/3.1-beta.tar.gz
--2024-04-06 18:22:12--  https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/archive/refs/tags/3.1-beta.tar.gz
Resolving github.com... 140.82.113.3
Connecting to github.com|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Dr-Gigavolt/dbus-aggregate-batteries/tar.gz/refs/tags/3.1-beta [following]
--2024-04-06 18:22:13--  https://codeload.github.com/Dr-Gigavolt/dbus-aggregate-batteries/tar.gz/refs/tags/3.1-beta
Resolving codeload.github.com... 140.82.114.9
Connecting to codeload.github.com|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘3.1-beta.tar.gz’

3.1-beta.tar.gz         [ <=>                ]  15.48K  --.-KB/s    in 0.1s    

2024-04-06 18:22:14 (152 KB/s) - ‘3.1-beta.tar.gz’ saved [15852]

root@einstein:/data/dbus-aggregate-batteries# ls
3.1-beta.tar.gz
root@einstein:/data/dbus-aggregate-batteries# tar xvf 3.1-beta.tar.gz 
dbus-aggregate-batteries-3.1-beta/
dbus-aggregate-batteries-3.1-beta/.gitattributes
dbus-aggregate-batteries-3.1-beta/LICENSE
dbus-aggregate-batteries-3.1-beta/README.md
dbus-aggregate-batteries-3.1-beta/aggregatebatteries.py
dbus-aggregate-batteries-3.1-beta/charge
dbus-aggregate-batteries-3.1-beta/dbusmon.py
dbus-aggregate-batteries-3.1-beta/functions.py
dbus-aggregate-batteries-3.1-beta/last_balancing
dbus-aggregate-batteries-3.1-beta/restart
dbus-aggregate-batteries-3.1-beta/restart_dbus-serial-battery
dbus-aggregate-batteries-3.1-beta/service/
dbus-aggregate-batteries-3.1-beta/service/run
dbus-aggregate-batteries-3.1-beta/settings.py
root@einstein:/data/dbus-aggregate-batteries# ls
3.1-beta.tar.gz                    dbus-aggregate-batteries-3.1-beta
root@einstein:/data/dbus-aggregate-batteries# nano dbus-aggregate-batteries-3.1-beta/
root@einstein:/data/dbus-aggregate-batteries# cd dbus-aggregate-batteries-3.1-beta/
root@einstein:/data/dbus-aggregate-batteries/dbus-aggregate-batteries-3.1-beta# ls
LICENSE                      last_balancing
README.md                    restart
aggregatebatteries.py        restart_dbus-serial-battery
charge                       service
dbusmon.py                   settings.py
functions.py
root@einstein:/data/dbus-aggregate-batteries/dbus-aggregate-batteries-3.1-beta# ls
LICENSE                      last_balancing
README.md                    restart
aggregatebatteries.py        restart_dbus-serial-battery
charge                       service
dbusmon.py                   settings.py
functions.py
root@einstein:/data/dbus-aggregate-batteries/dbus-aggregate-batteries-3.1-beta# cd ..
root@einstein:/data/dbus-aggregate-batteries# ls
3.1-beta.tar.gz                    dbus-aggregate-batteries-3.1-beta
root@einstein:/data/dbus-aggregate-batteries# cd ..
root@einstein:/data# ls
BatteryAggregator         dbus-serialbattery.log    rc.local
GuiMods                   etc                       rcS.local
SetupHelper               home                      setupOptions
Users                     keys                      themes
conf                      log                       var
db                        lost+found                venus
dbus-aggregate-batteries  rc                        vrmfilescache
root@einstein:/data# rm dbus-aggregate-batteries/
rm: 'dbus-aggregate-batteries' is a directory
root@einstein:/data# rm -d dbus-aggregate-batteries/
rm: invalid option -- 'd'
BusyBox v1.31.1 (2024-03-29 15:37:51 UTC) multi-call binary.

Usage: rm [-irf] FILE...
root@einstein:/data# ls
BatteryAggregator         dbus-serialbattery.log    rc.local
GuiMods                   etc                       rcS.local
SetupHelper               home                      setupOptions
Users                     keys                      themes
conf                      log                       var
db                        lost+found                venus
dbus-aggregate-batteries  rc                        vrmfilescache
root@einstein:/data# unlink dbus-aggregate-batteries/
unlink: can't remove file 'dbus-aggregate-batteries/': Is a directory
root@einstein:/data# rm -d dbus-aggregate-batteries/
rm: invalid option -- 'd'
BusyBox v1.31.1 (2024-03-29 15:37:51 UTC) multi-call binary.

Usage: rm [-irf] FILE...
root@einstein:/data# rm -r dbus-aggregate-batteries/
root@einstein:/data# ls
BatteryAggregator       etc                     rcS.local
GuiMods                 home                    setupOptions
SetupHelper             keys                    themes
Users                   log                     var
conf                    lost+found              venus
db                      rc                      vrmfilescache
dbus-serialbattery.log  rc.local
root@einstein:/data# ls
BatteryAggregator       etc                     rcS.local
GuiMods                 home                    setupOptions
SetupHelper             keys                    themes
Users                   log                     var
conf                    lost+found              venus
db                      rc                      vrmfilescache
dbus-serialbattery.log  rc.local
root@einstein:/data# wget https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/archive/refs/tags/3.1-beta.tar.gz
--2024-04-06 18:27:23--  https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/archive/refs/tags/3.1-beta.tar.gz
Resolving github.com... 140.82.113.4
Connecting to github.com|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Dr-Gigavolt/dbus-aggregate-batteries/tar.gz/refs/tags/3.1-beta [following]
--2024-04-06 18:27:23--  https://codeload.github.com/Dr-Gigavolt/dbus-aggregate-batteries/tar.gz/refs/tags/3.1-beta
Resolving codeload.github.com... 140.82.114.9
Connecting to codeload.github.com|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘3.1-beta.tar.gz’

3.1-beta.tar.gz         [ <=>                ]  15.48K  --.-KB/s    in 0.07s   

2024-04-06 18:27:24 (213 KB/s) - ‘3.1-beta.tar.gz’ saved [15852]

root@einstein:/data# ls
3.1-beta.tar.gz         dbus-serialbattery.log  rc.local
BatteryAggregator       etc                     rcS.local
GuiMods                 home                    setupOptions
SetupHelper             keys                    themes
Users                   log                     var
conf                    lost+found              venus
db                      rc                      vrmfilescache
root@einstein:/data# tar xvf 3.1-beta.tar.gz 
dbus-aggregate-batteries-3.1-beta/
dbus-aggregate-batteries-3.1-beta/.gitattributes
dbus-aggregate-batteries-3.1-beta/LICENSE
dbus-aggregate-batteries-3.1-beta/README.md
dbus-aggregate-batteries-3.1-beta/aggregatebatteries.py
dbus-aggregate-batteries-3.1-beta/charge
dbus-aggregate-batteries-3.1-beta/dbusmon.py
dbus-aggregate-batteries-3.1-beta/functions.py
dbus-aggregate-batteries-3.1-beta/last_balancing
dbus-aggregate-batteries-3.1-beta/restart
dbus-aggregate-batteries-3.1-beta/restart_dbus-serial-battery
dbus-aggregate-batteries-3.1-beta/service/
dbus-aggregate-batteries-3.1-beta/service/run
dbus-aggregate-batteries-3.1-beta/settings.py
root@einstein:/data# l
-sh: l: command not found
root@einstein:/data# ls
3.1-beta.tar.gz                    keys
BatteryAggregator                  log
GuiMods                            lost+found
SetupHelper                        rc
Users                              rc.local
conf                               rcS.local
db                                 setupOptions
dbus-aggregate-batteries-3.1-beta  themes
dbus-serialbattery.log             var
etc                                venus
home                               vrmfilescache
root@einstein:/data# mv dbus-aggregate-batteries-3.1-beta/ /dbus-aggregate-batteries
root@einstein:/data# ls
3.1-beta.tar.gz         dbus-serialbattery.log  rc.local
BatteryAggregator       etc                     rcS.local
GuiMods                 home                    setupOptions
SetupHelper             keys                    themes
Users                   log                     var
conf                    lost+found              venus
db                      rc                      vrmfilescache
root@einstein:/data# ls
3.1-beta.tar.gz         dbus-serialbattery.log  rc.local
BatteryAggregator       etc                     rcS.local
GuiMods                 home                    setupOptions
SetupHelper             keys                    themes
Users                   log                     var
conf                    lost+found              venus
db                      rc                      vrmfilescache
root@einstein:/data# cd /
root@einstein:/# ls
Settings                  home                      run
bin                       lib                       sbin
boot                      lost+found                service
data                      media                     sys
dbus-aggregate-batteries  mnt                       tmp
dev                       opt                       usr
etc                       proc                      var
root@einstein:/# mv dbus-aggregate-batteries/ /data/dbus-aggregate-batteries
root@einstein:/# ls
Settings    dev         lost+found  proc        sys
bin         etc         media       run         tmp
boot        home        mnt         sbin        usr
data        lib         opt         service     var
root@einstein:/# cd data/dbus-aggregate-batteries/
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      last_balancing
README.md                    restart
aggregatebatteries.py        restart_dbus-serial-battery
charge                       service
dbusmon.py                   settings.py
functions.py
root@einstein:/data/dbus-aggregate-batteries# chmod 744 ./service/run 
root@einstein:/data/dbus-aggregate-batteries# chmod 744 ./restart
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      last_balancing
README.md                    restart
aggregatebatteries.py        restart_dbus-serial-battery
charge                       service
dbusmon.py                   settings.py
functions.py
root@einstein:/data/dbus-aggregate-batteries# nano settings.py 
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      aggregatebatteries.py        dbusmon.py                   last_balancing               restart_dbus-serial-battery  settings.py
README.md                    charge                       functions.py                 restart                      service
root@einstein:/data/dbus-aggregate-batteries# nano charge 
root@einstein:/data/dbus-aggregate-batteries# nano charge 
root@einstein:/data/dbus-aggregate-batteries# cd /
root@einstein:/# cd /data/dbus-aggregate-batteries/service/
root@einstein:/data/dbus-aggregate-batteries/service# ls
run
root@einstein:/data/dbus-aggregate-batteries/service# cd /
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# cd data/
root@einstein:/data# ls
3.1-beta.tar.gz           Users                     dbus-serialbattery.log    log                       rcS.local                 venus
BatteryAggregator         conf                      etc                       lost+found                setupOptions              vrmfilescache
GuiMods                   db                        home                      rc                        themes
SetupHelper               dbus-aggregate-batteries  keys                      rc.local                  var
root@einstein:/data# nano rc.local 
root@einstein:/data# shutdown -r now

Broadcast message from root@einstein (pts/2) (Sat Apr  6 18:43:47 2024):

The system is going down for reboot NOW!
root@einstein:/data# client_loop: send disconnect: Broken pipe
padre@MacBookPro ~ % ssh root@192.168.2.133
root@192.168.2.133's password: 
Last login: Sat Apr  6 18:44:30 2024
root@einstein:~# cd /
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# cd data/dbus-aggregate-batteries/
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      aggregatebatteries.py        dbusmon.py                   last_balancing               restart_dbus-serial-battery  settings.py
README.md                    charge                       functions.py                 restart                      service
root@einstein:/data/dbus-aggregate-batteries# nano README.md 
root@einstein:/data/dbus-aggregate-batteries# LS
-sh: LS: command not found
root@einstein:/data/dbus-aggregate-batteries# nano aggregatebatteries.py 
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      aggregatebatteries.py        dbusmon.py                   last_balancing               restart_dbus-serial-battery  settings.py
README.md                    charge                       functions.py                 restart                      service
root@einstein:/data/dbus-aggregate-batteries# ./restart 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
root@einstein:/data/dbus-aggregate-batteries# sh restart
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      aggregatebatteries.py        dbusmon.py                   last_balancing               restart_dbus-serial-battery  settings.py
README.md                    charge                       functions.py                 restart                      service
root@einstein:/data/dbus-aggregate-batteries# cd /
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# cd service/
root@einstein:/service# ls
PackageManager              dbus-fronius                dbus-systemcalc-py          mqtt-rpc                    ssh-tunnel                  venus-html5-logger
can-bus-bms.can1            dbus-generator-starter      dbus-tempsensor-relay       netmon                      start-gui                   venus-platform
dbus-adc                    dbus-modbus-client          dbus-vebus-to-pvinverter    nginx                       vecan-dbus.can0             vrmlogger
dbus-ble-sensors            dbus-pump                   flashmq                     openssh                     vedirect-interface.ttyS5    websockify-c
dbus-blebattery.0           dbus-serialbattery.ttyUSB0  hub4control                 ppp                         vedirect-interface.ttyS6
dbus-blebattery.1           dbus-serialbattery.ttyUSB1  llmnrd                      serial-starter              vedirect-interface.ttyS7
dbus-blebattery.2           dbus-serialbattery.ttyUSB2  localsettings               service-advertiser          venus-access
dbus-digitalinputs          dbus-shelly                 mk2-dbus.ttyS4              simple-upnpd                venus-button-handler
root@einstein:/service# cd /
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# cd data/
root@einstein:/data# ls
3.1-beta.tar.gz           Users                     dbus-serialbattery.log    log                       rcS.local                 venus
BatteryAggregator         conf                      etc                       lost+found                setupOptions              vrmfilescache
GuiMods                   db                        home                      rc                        themes
SetupHelper               dbus-aggregate-batteries  keys                      rc.local                  var
root@einstein:/data# nano dbus-serialbattery.log 
root@einstein:/data# nano BatteryAggregator/
root@einstein:/data# cd BatteryAggregator/
root@einstein:/data/BatteryAggregator# ls
LICENSE              __pycache__          dummy_battery.py     gitHubInfo           script_utils.py      setup
README.md            battery_service.py   ext                  packageCheckVersion  service              version
root@einstein:/data/BatteryAggregator# nano README.md 
root@einstein:/data/BatteryAggregator# cd /
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# cd data/
root@einstein:/data# ls
3.1-beta.tar.gz           Users                     dbus-serialbattery.log    log                       rcS.local                 venus
BatteryAggregator         conf                      etc                       lost+found                setupOptions              vrmfilescache
GuiMods                   db                        home                      rc                        themes
SetupHelper               dbus-aggregate-batteries  keys                      rc.local                  var
root@einstein:/data# cd/
-sh: cd/: No such file or directory
root@einstein:/data# ls
3.1-beta.tar.gz           Users                     dbus-serialbattery.log    log                       rcS.local                 venus
BatteryAggregator         conf                      etc                       lost+found                setupOptions              vrmfilescache
GuiMods                   db                        home                      rc                        themes
SetupHelper               dbus-aggregate-batteries  keys                      rc.local                  var
root@einstein:/data# cd log/
root@einstein:/data/log# ls
BatteryAggregator            dbus-fronius                 dbus-qwacs                   gui                          mqtt-rpc                     vedirect.ttyUSB0
PackageManager               dbus-fzsonick-48tl.ttyUSB0   dbus-serialbattery.TTY       hiawatha                     netmon                       vedirect.ttyUSB1
SetupHelper                  dbus-fzsonick-48tl.ttyUSB1   dbus-serialbattery.ttyUSB0   hostapd                      nginx                        vedirect.ttyUSB2
boot                         dbus-fzsonick-48tl.ttyUSB2   dbus-serialbattery.ttyUSB1   hub4control                  node-red-venus               venus-access
boot~                        dbus-generator-starter       dbus-serialbattery.ttyUSB2   lastlog                      serial-starter               venus-button-handler
can-bus-bms.can1             dbus-imt-si-rs485tc.ttyUSB0  dbus-shelly                  localsettings                service-advertiser           venus-html5-app
dbus-adc                     dbus-imt-si-rs485tc.ttyUSB1  dbus-systemcalc-py           messages                     simple-upnpd                 venus-html5-logger
dbus-ble-sensors             dbus-imt-si-rs485tc.ttyUSB2  dbus-tempsensor-relay        messages.0                   ssh-tunnel                   venus-platform
dbus-blebattery.0            dbus-modbus-client           dbus-vebus-to-pvinverter     messages.1                   sshd                         vesmart-server
dbus-blebattery.1            dbus-modbus-client.ttyUSB0   dmesg                        messages.2                   start-gui                    vrmlogger
dbus-blebattery.2            dbus-modbus-client.ttyUSB1   dmesg.old                    messages.3                   swupdate                     watchdog_processlist.txt
dbus-cgwacs.ttyUSB0          dbus-modbus-client.ttyUSB2   flashmq                      messages.4                   vecan-dbus.can0              websockify-c
dbus-cgwacs.ttyUSB1          dbus-modbustcp               gps-dbus.ttyUSB0             messages.5                   vedirect.ttyS5               wtmp
dbus-cgwacs.ttyUSB2          dbus-mqtt                    gps-dbus.ttyUSB1             mk2_dbus.ttyS4               vedirect.ttyS6
dbus-digitalinputs           dbus-mqtt-battery            gps-dbus.ttyUSB2             mosquitto                    vedirect.ttyS7
root@einstein:/data/log# nano dbus-
dbus-adc/                    dbus-cgwacs.ttyUSB1/         dbus-fzsonick-48tl.ttyUSB2/  dbus-modbus-client.ttyUSB0/  dbus-qwacs/                  dbus-systemcalc-py/
dbus-ble-sensors/            dbus-cgwacs.ttyUSB2/         dbus-generator-starter/      dbus-modbus-client.ttyUSB1/  dbus-serialbattery.TTY/      dbus-tempsensor-relay/
dbus-blebattery.0/           dbus-digitalinputs/          dbus-imt-si-rs485tc.ttyUSB0/ dbus-modbus-client.ttyUSB2/  dbus-serialbattery.ttyUSB0/  dbus-vebus-to-pvinverter/
dbus-blebattery.1/           dbus-fronius/                dbus-imt-si-rs485tc.ttyUSB1/ dbus-modbustcp/              dbus-serialbattery.ttyUSB1/  
dbus-blebattery.2/           dbus-fzsonick-48tl.ttyUSB0/  dbus-imt-si-rs485tc.ttyUSB2/ dbus-mqtt/                   dbus-serialbattery.ttyUSB2/  
dbus-cgwacs.ttyUSB0/         dbus-fzsonick-48tl.ttyUSB1/  dbus-modbus-client/          dbus-mqtt-battery/           dbus-shelly/                 
root@einstein:/data/log# nano dbus-
dbus-adc/                    dbus-cgwacs.ttyUSB1/         dbus-fzsonick-48tl.ttyUSB2/  dbus-modbus-client.ttyUSB0/  dbus-qwacs/                  dbus-systemcalc-py/
dbus-ble-sensors/            dbus-cgwacs.ttyUSB2/         dbus-generator-starter/      dbus-modbus-client.ttyUSB1/  dbus-serialbattery.TTY/      dbus-tempsensor-relay/
dbus-blebattery.0/           dbus-digitalinputs/          dbus-imt-si-rs485tc.ttyUSB0/ dbus-modbus-client.ttyUSB2/  dbus-serialbattery.ttyUSB0/  dbus-vebus-to-pvinverter/
dbus-blebattery.1/           dbus-fronius/                dbus-imt-si-rs485tc.ttyUSB1/ dbus-modbustcp/              dbus-serialbattery.ttyUSB1/  
dbus-blebattery.2/           dbus-fzsonick-48tl.ttyUSB0/  dbus-imt-si-rs485tc.ttyUSB2/ dbus-mqtt/                   dbus-serialbattery.ttyUSB2/  
dbus-cgwacs.ttyUSB0/         dbus-fzsonick-48tl.ttyUSB1/  dbus-modbus-client/          dbus-mqtt-battery/           dbus-shelly/                 
root@einstein:/data/log# nano dbus-serialbattery.ttyUSB2
root@einstein:/data/log# cd dbus-serialbattery.ttyUSB2
root@einstein:/data/log/dbus-serialbattery.ttyUSB2# ls
@40000000660cab9b07fe12ec.u  @40000000660ea79737d7c0e4.s  @4000000066110e3201a6a92c.s  current                      lock                         state
root@einstein:/data/log/dbus-serialbattery.ttyUSB2# nano current 
root@einstein:/data/log/dbus-serialbattery.ttyUSB2# nano \@40000000660cab9b07fe12ec.u 
root@einstein:/data/log/dbus-serialbattery.ttyUSB2# cd /
root@einstein:/# cd data/log/serial-starter/
root@einstein:/data/log/serial-starter# ls
@4000000065de44fb204a0b6c.s  @4000000065fb7cea25f389bc.s  @40000000660cab8702fb159c.u  current                      lock                         state
root@einstein:/data/log/serial-starter# nano current 
root@einstein:/data/log/serial-starter# cd/
-sh: cd/: No such file or directory
root@einstein:/data/log/serial-starter# cd data
-sh: cd: data: No such file or directory
root@einstein:/data/log/serial-starter# cd /
root@einstein:/# ls
Settings    boot        dev         home        lost+found  mnt         proc        sbin        sys         usr
bin         data        etc         lib         media       opt         run         service     tmp         var
root@einstein:/# cd data/dbus-aggregate-batteries/
root@einstein:/data/dbus-aggregate-batteries# ls
LICENSE                      aggregatebatteries.py        dbusmon.py                   last_balancing               restart_dbus-serial-battery  settings.py
README.md                    charge                       functions.py                 restart                      service
root@einstein:/data/dbus-aggregate-batteries# nano settings.py 

  GNU nano 4.9.3                                                                           settings.py                                                                                     
# Version 3.1

#######################################
########## Hardware settings ##########
#######################################

NR_OF_BATTERIES = 3                                     # Nr. of physical batteries to be aggregated. Smart shunt for battery current is not needed and not supported.
NR_OF_CELLS_PER_BATTERY = 4
NR_OF_MPPTS = 2                                         # Nr. of MPPTs
DC_LOADS = False                                        # If DC loads with Smart Shunt present, can be used for total current measurement
INVERT_SMARTSHUNT = False                               # False: Current subtracted, True: Current added

#######################################
############ DBus settings ############
#######################################

BATTERY_SERVICE_NAME = 'com.victronenergy.battery'	# Key world to identify services of physical Serial Batteries (and SmartShunt if available)
BATTERY_PRODUCT_NAME_PATH = '/Battery'                  # Path of Battery Product Name
BATTERY_PRODUCT_NAME = 'SerialBattery'                  # Key world to identify the batteries (to exclude SmartShunt)
BATTERY_INSTANCE_NAME_PATH = '/CustomName'              # if CustomName doesn't exist, set '/ProductName'
MULTI_KEY_WORD = 'com.victronenergy.vebus'              # Key world to identify service of Multis/Quattros (or cluster of them)
MPPT_KEY_WORD = 'com.victronenergy.solarcharger'        # Key world to identify services of solar chargers
SMARTSHUNT_NAME_KEY_WORD = 'SmartShunt'                 # Key world to identify services of SmartShunt

SEARCH_TRIALS = 10                                      # Trials to identify of all batteries before exit and restart
READ_TRIALS = 10                                        # Trials to get consistent data of all batteries before exit and restart

#######################################
############## Options ################
#######################################

CURRENT_FROM_VICTRON = True                             # If True, the current measurement by Multis/Quattros and MPPTs is taken instead of BMS.
                                                        # Necessary for JK BMS due to poor precision.
OWN_SOC = True                                          # If True, the self calculated charge indicators are taken instead of BMS
ZERO_SOC = True                                         # Allow zeroing charge counter at MIN_CELL_VOLTAGE. At full battery it is always set to 100%.
CHARGE_SAVE_PRECISION = 0.0025                          # Trade-off between save precision and file access frequency

#######################################
##### Charge/Discharge parameters #####
#######################################

                                                                                     [ Read 88 lines ]
^G Get Help	 ^O Write Out     ^W Where Is	   ^K Cut Text      ^J Justify       ^C Cur Pos       M-U Undo         M-A Mark Text    M-] To Bracket   M-Q Previous     ^B Back
^X Exit          ^R Read File     ^\ Replace	   ^U Paste Text    ^T To Spell      ^_ Go To Line    M-E Redo         M-6 Copy Text    ^Q Where Was     M-W Next         ^F Forward

**Comment by coca7** [comment]
There is no log file created after I installed, edited the settings.py and rc.local and rebooted.

**Comment by Dr-Gigavolt** [comment]
Hello, have you perhaps forgot to create the symbolic link?
 ln -s /data/dbus-aggregate-batteries/service /service/dbus-aggregate-batteries into /data/rc.local
 
I've just released last commit, here you can download the stuff "install" according Readme file.
https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/releases/tag/3.1.1-beta

**Comment by Dr-Gigavolt** [comment]
wget from /data should work too:
sudo wget https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/archive/refs/tags/3.1.1-beta.tar.gz
sudo tar -xvf 3.1.1-beta.tar.gz
sudo mv dbus-aggregate-batteries-3.1.1-beta dbus-aggregate-batteries
cd dbus-aggregate-batteries
sudo chmod 777 restart ./service/run

and then open /data/rc.local with a text editor and add 
_ln -s /data/dbus-aggregate-batteries/service /service/dbus-aggregate-batteries_
line.

**Comment by Dr-Gigavolt** [comment]
The log file aggregatebatteries.log should be created in /data/dbus-aggregate-batteries

**Comment by coca7** [comment]
I did add the line in to rc.local but I have a question about it.
does the past start with "In" or "-s". I started with -s.  Everything else you suggested I did except I didn't run the command with sudo.  Also the readme had said to chmod 744, whereas here you said to chmod 777.

**Comment by Dr-Gigavolt** [comment]
The line begins with ln (command), -s is a parameter. The permission 744 is ok (777 works as well, but unnecessarily too much rights).

**Comment by coca7** [comment]
The driver runs, but it doesn't find any of the batteries.  I think I have the DBUS settings wrong:

Here is what the log says:

>  INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
> INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB2, scanning and storing items
> INFO:dbusmonitor:	com.victronenergy.battery.ttyUSB2 has device instance 4
> INFO:dbusmonitor:Found: com.victronenergy.settings, scanning and storing items
> INFO:dbusmonitor:	com.victronenergy.settings has device instance 0
> INFO:root:Mon Apr  8 13:26:01 2024: Searching Settings: Trial Nr. 1
> INFO:dbusmonitor:Found: com.victronenergy.solarcharger.ttyS5, scanning and storing items
> INFO:root:Mon Apr  8 13:26:01 2024: com.victronenergy.settings found.
> INFO:dbusmonitor:       com.victronenergy.solarcharger.ttyS5 has device instance 278
> INFO:dbusmonitor:Found: com.victronenergy.solarcharger.ttyS6, scanning and storing items
> INFO:dbusmonitor:	com.victronenergy.solarcharger.ttyS6 has device instance 279
> INFO:dbusmonitor:Found: com.victronenergy.system, scanning and storing items
> INFO:dbusmonitor:	com.victronenergy.system has device instance 0
> INFO:dbusmonitor:Found: com.victronenergy.vebus.ttyS4, scanning and storing items
> INFO:dbusmonitor:	com.victronenergy.vebus.ttyS4 has device instance 276
> INFO:dbusmonitor:Found: com.victronenergy.battery.ttyS7, scanning and storing items
> INFO:dbusmonitor:       com.victronenergy.battery.ttyS7 has device instance 277
> INFO:dbusmonitor:Found: com.victronenergy.battery.aggregate, scanning and storing items
> INFO:dbusmonitor:       com.victronenergy.battery.aggregate has device instance 0
> INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0, scanning and storing items
> INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0 has device instance 3
> INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB1, scanning and storing items
> INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB1 has device instance 2
> INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
> INFO:root:Mon Apr  8 13:26:06 2024: Searching batteries: Trial Nr. 1
> INFO:root:Mon Apr  8 13:26:06 2024: 0 batteries found.
> INFO:root:Mon Apr  8 13:26:11 2024: Searching batteries: Trial Nr. 2
> INFO:root:Mon Apr  8 13:26:11 2024: 0 batteries found.
> 

Here is what I put in the settings.py

```
 BATTERY_SERVICE_NAME = 'com.victronenergy.battery'	# Key world to identify services of physical Serial Batteries (and SmartShunt if available)
 BATTERY_PRODUCT_NAME_PATH = '/dev/ttyUSB'                  # Path of Battery Product Name
 BATTERY_PRODUCT_NAME = 'Battery'                  # Key world to identify the batteries (to exclude SmartShunt)
 BATTERY_INSTANCE_NAME_PATH = '/SerialBattery(LLT/JBD)'              # if CustomName doesn't exist, set '/ProductName'
 MULTI_KEY_WORD = 'com.victronenergy.vebus'              # Key world to identify service of Multis/Quattros (or cluster of them)
 MPPT_KEY_WORD = 'com.victronenergy.solarcharger'        # Key world to identify services of solar chargers
 SMARTSHUNT_NAME_KEY_WORD = 'SmartShunt'                 # Key world to identify services of SmartShunt

```

Here is what I have for one of my batteries in dbus-spy

 
<img width="1627" alt="Screenshot 2024-04-08 at 8 36 56 AM" src="https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/assets/2902641/6276288f-74e1-4169-bf7a-9a52be51d37f">
<img width="1627" alt="Screenshot 2024-04-08 at 8 36 32 AM" src="https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/assets/2902641/53d47225-cf9c-454a-8d08-b05df3bdc23a">

**Comment by Dr-Gigavolt** [comment]
The product name path is wrong. It is a dBus path, not driver path in Linux. The default is correct: BATTERY_PRODUCT_NAME_PATH = '/ProductName'
