### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by reivis** [Dr-Gigavolt/dbus-aggregate-batteries#70]
Hello,

How can I uninstall dbus-aggregate-batteries?

**Comment by Dr-Gigavolt** [comment]
Execute uninstall.sh

**Comment by reivis** [comment]
Nope, "command not found".
I go to the directory witt cd command and execute uninstall.sh and got  above message!

**Comment by Dr-Gigavolt** [comment]
sh ./uninstall.sh

**Comment by Dr-Gigavolt** [comment]
Das command ist sh (shell), ./<shell_file> is the relative path if you are in the right directory.
