### ISSUE TITLE
Code indent error in version 3.3

### ISSUE THREAD

**Issue by coca7** [Dr-Gigavolt/dbus-aggregate-batteries#73]
After installing version 3.3 I get an error:

IndentationError: unindent does not match any outer indentation level
  File "/data/dbus-aggregate-batteries/aggregatebatteries.py", line 832
    sys.exit()
 
When I fix in my individual aggregate batteries.py file I get further errors.  I think my settings for indentation might be different.

**Comment by Dr-Gigavolt** [comment]
Thanks, same at me. I surely pressed tab just before commit. Now fixed.
