### ISSUE TITLE
Driver crashes when SOC is 0%

### ISSUE THREAD

**Issue by regu-tech** [Dr-Gigavolt/dbus-aggregate-batteries#74]
Hello, 

we are one step ahead, it seems that the aggregate battery is shown correctly in the overview window:
![image](https://github.com/user-attachments/assets/09e6d449-c0a8-4426-bd22-b4d181f7edbd)

but the "Aggregate Batteries" menu point is gone when all batteries are empty
![image](https://github.com/user-attachments/assets/6261d6ca-d552-4cb4-8966-711de6c63212)

The Log shows many of these errors:

`IndentationError: unindent does not match any outer indentation level
  File "/data/dbus-aggregate-batteries/aggregatebatteries.py", line 832
    sys.exit()
             ^
IndentationError: unindent does not match any outer indentation level
  File "/data/dbus-aggregate-batteries/aggregatebatteries.py", line 832
    sys.exit()
             ^
IndentationError: unindent does not match any outer indentation level
  File "/data/dbus-aggregate-batteries/aggregatebatteries.py", line 832
    sys.exit()
`

_Originally posted by @regu-tech in https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/issues/48#issuecomment-2463325530_

**Comment by coca7** [comment]
There was an error with this that was corrected earlier today.  Can you navigate to the directory and install it again using ".'install.sh". I think that will resolve your issue.  You might also have to put your settings back in settings.new-version.py and restart your device.

**Comment by regu-tech** [comment]
Good morning,

thanks for your help, now it is working.

I have only replaced the new (changed) files since the last install and has done a local-install.sh 

best regards
Steffen
